### ISSUE TITLE
Restart pool upon failure of resources from init_pool

### ISSUE THREAD

**Issue by davydog187** [dashbitco/nimble_pool#24]
Hello 👋🏼 

I would like to caveat this issue that I may have a use-case that is not a good fit for `NimblePool`. I'm posting in the chance that it is and there is simply an API change that will help.

## Problem Statement
I am building a small internal library for publishing analytics events through AMQP. I would like to minimize the number of open AMQP connections by multiplexing through [AMQP Channels](https://www.rabbitmq.com/channels.html#lifecycle). At application startup, I would like to open some number of connections, each with a factor multiple of channels. Then application publishers can make use of the active channels.

## Solution using AMQP + NimblePool

1. Open a connection in `init_pool/1`

```elixir
  @impl NimblePool
  def init_pool(opts) do
    case AMQP.Connection.open(opts) do
      {:ok, conn} ->
        Process.monitor(conn.pid)
        {:ok, conn}

      {:error, error} ->
        {:stop, error}
    end
  end
```

2. Open a channel from the connection in each worker

```elixir
  @impl NimblePool
  def init_worker(conn) do
    async = fn ->
      {:ok, channel} = AMQP.Channel.open(conn)
      channel
    end

    {:async, async, conn}
  end
```

3. Publish function checks out a channel and publishes

```elixir
  def publish(value) do
    NimblePool.checkout!(MyPool, :checkout, fn _pool, channel ->
      response = AMQP.Basic.publish(channel, "exchange", "", value)

      {response, channel}
    end)
  end
```

## Issues with this approach

1. `init_pool/1` blocks the `init/1` callback of the pool
2. If the AMQP connection dies, there is not a way to re-initialize the connection or kill the pool

## Questions
1. Is my usecase not a good fit for NimblePool?

From the docs

> NimblePool may not be a good option to manage processes. Also avoid using NimblePool to manage resources that support multiplexing, such as HTTP 2 connections (in fact, pools are not a good option to manage resources with multiplexing in general).

2. Assuming its not, I'm happy to improve the documentation to give more detail as to why. Any advice on what would be a better approach for multiplexing over pools would be appreciated

Thank you :)

**Comment by josevalim** [comment]
Yes, pools are not good for multiplexing cases because multiplexing means they can support many clients at once. Pools are necessary when the thing you are polling only supports one request at a time.

If you need multiplexing, then you can start N processes and pick one randomly. The PartitionSupervisor in Elixir v1.14 is meant to make that super easy: https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/partition_supervisor.ex

**Comment by davydog187** [comment]
Thanks for the reply @josevalim. I suppose that will work although I wanted to avoid opening N connections, its probably ok though

**Comment by josevalim** [comment]
@davydog187 from what i hear a single AMPQ channel can handle a lot of things happening currently. You most likely need a single connection and you can make the parameter customizable.

**Comment by davydog187** [comment]
Good call, I'll benchmark that assumption. I will also submit a docs PR for this asap
