### ISSUE TITLE
Feature request: checkout and checkin functions

### ISSUE THREAD

**Issue by hissssst** [dashbitco/nimble_pool#31]
### Overview

Sometimes `checkout!/4` function does not suit the needs of a program which wants to manually check resource in and out. Functions like `checkin/4` and `checkout/3` can solve this problem

### Example

You want to take a resource and create a `Stream` which returns the resource back upon completion
With functions like `checkin/3` and `checkout/3` this would be possible

```elixir
Stream.resource(
  fn -> NimblePool.checkout(pool, :checkout, timeout) end,
  fn resource -> get_part(resource) end,
  fn resource -> NimblePool.checkin(pool, :checkin, resource, timeout) end
)
```

**Comment by hissssst** [comment]
@josevalim I can implement the feature if you agree on the design

**Comment by josevalim** [comment]
Closing as there was no progress on this for a year.
