### ISSUE TITLE
How to make application stop when `init_worker/1` callback fails?

### ISSUE THREAD

**Issue by nallwhy** [dashbitco/nimble_pool#36]
I made a library that help to use Python, Ruby in Elixir applications.

https://github.com/nallwhy/doumi_port

But it makes error infinitly when it fails to initialize worker in `init_worker/1` callback of NimblePool.

For example, it crashes with `MatchError` if there is no `python` installed.

`lib/doumi/port/pool.ex`:63
```elixir
  @impl NimblePool
  def init_worker({port_module, port_opts} = pool_state) do
    {:ok, port} = port_module.start(port_opts) # <-- here

    {:ok, %{port_module: port_module, port: port}, pool_state}
  end
```

`init_worker/1` allows to return only `{:ok, _, _}` or `{:asnyc, _}`, no error case.

I want the Supervisor of NimblePool crashes, and for it to propagate and terminate the application if initializing worker continues to fail.

How can I implement it?

**Comment by josevalim** [comment]
I think you can try returning:

     {:invalid_state, "python not detected"}

and that will force a crash for now but it is not necessarily the best. A PR to add a `{:stop reason}` is welcome.
