### ISSUE TITLE
New worker callback for canceled requests

### ISSUE THREAD

**Issue by oliveigah** [dashbitco/nimble_pool#43]
On finch, https://github.com/sneako/finch/pull/267 we received a bug report regarding the metrics counter that can be solved by a new worker callback.

Our strategy to keep pool metrics on finch is simple. Whenever a checkout happens increase the metric and decrease on checkin. The problem happens whenever a checkout happens without a checkin counter part.

Reading nimble_pool's code the main way I can see this happening is here: https://github.com/dashbitco/nimble_pool/blob/deae8ffdb52ce5265a68299eea3e5074f1e8d5a7/lib/nimble_pool.ex#L441-L444

By forcing the checkout function code raise we can reproduce this bug on finch (see the the related PR for more details).

My proposal is to add a new callback `handle_cancel(worker_state, pool_state)`  and also decrease the metric in it on finch.

For my local test validation on finch I've called this callback it as the firt line of this function and it solved the bug. https://github.com/dashbitco/nimble_pool/blob/deae8ffdb52ce5265a68299eea3e5074f1e8d5a7/lib/nimble_pool.ex#L748

But I do not know if this is the proper place for it.  What is your thoughts?

As soon as you agree on an implementation I can work on a PR.

Let me know if you have any other suggestion on how we can keep the metrics on the finch side in order to solve the problem without implement this new callback! 

Thanks! :smiley:

**Comment by josevalim** [comment]
Yes, it sounds good to me. I would call it `handle_cancelled` and, besides the usual arguments, I would pass an atom saying it was `:queued` or `:checked_out`. PRs welcome :heart:
