### ISSUE TITLE
new pool callback for idle verification 

### ISSUE THREAD

**Issue by oliveigah** [dashbitco/nimble_pool#46]
In Finch, we have a bug report regarding idle termination: https://github.com/sneako/finch/issues/291

To address this, I added the last checkout timestamp to the pool state and verified it using the currently available `handle_ping/2` callback for workers: https://github.com/sneako/finch/pull/292

While `handle_ping/2` works well for managing individual idle resources, it’s less suited for making pool-wide decisions, as it lacks full context of the pool’s idle state.

For example, consider a pool with: `resource 1 (idle), resource 2 (just checked in, not idle)`

If idle verification triggers `handle_ping/2` for resource 1, there’s no way to confirm if the entire pool is idle and should be terminated.

Since this seems to be a more general problem, I propose adding a `handle_ping/1` callback for the pool itself, which would trigger after a given timeout without checkouts or check-ins and therefore provides better semantics for pool termination scenarios. 

This would also prevent clients like Finch from needing to track internal metadata for the pool, such as the last checkout timestamp.

Let me know your thoughts! If you agree, I can start to work on a PR.

**Comment by josevalim** [comment]
Are we sure adding a handle_ping/1 would be better? Now NimblePool would need to check when all resources have not been used, requiring the pool to track more additional state. Between tracking the state of all resources and a timestamp, it feels the timestamp is a more lightweight approach?

**Comment by oliveigah** [comment]
I was thinking about a more generic approach, where `handle_ping/1` would only trigger after the pool has been idle—no checkouts or check-ins—for more than X time.

With this approach, `handle_ping/1` would provide exactly the semantics we need: we could terminate the pool as soon as it’s called, with no extra data or checks required.

The difference is in the semantics:

`handle_ping/2`: triggers for each worker when it has been idle for more than X time.

handle_ping/1: triggers for the entire pool when it has been idle (no checkouts or check-ins) for more than X time.

The `handle_ping/1` semantics seem far more suited to pool termination scenarios, and they would simplify cases where we need to terminate the pool due to inactivity.

**Comment by josevalim** [comment]
@oliveigah since my concern is the complexity of implementation, would you like to send a PR? My gut feeling still thinks that handle_ping/2 + last_checkout_timeout is enough, but perhaps the implementation here is so simple that it won't really matter.

**Comment by oliveigah** [comment]
Sure! Gonna take a look at it!

Regarding implementation I think it would be simple and similar to what I've done on finch.

I was thinking about just have an extra field on the state `last_activity_ts` and compare on it inside a periodic check to see if we shoul call `handle_ping/1` callback or not.

**Comment by oliveigah** [comment]
@josevalim, recently we had a new issue on Finch: https://github.com/sneako/finch/issues/311, and I believe this new callback might help address it.

The problem stems from the current limitation where the handle_ping callback only applies to workers, not the entire pool. Because of this, we have no way to terminate empty pools.

This limitation is even mentioned in the documentation:

On lazy pools, if no worker is currently in the pool, the callback will never be called. Therefore, you cannot rely on this callback to terminate empty lazy pools.

This new proposed callback might help us achieve the desired behavior!
Do you think it would be worth reopening this and reconsidering the previous PR? Let me know your thoughts!

**Comment by josevalim** [comment]
Thank you for the additional context.

I think we would need to be very careful with this, even if you have this callback, what happens if a checkout request is received between the timer going off and you terminating?

In those cases, you need several steps, where the first one is to remove the pool from whatever process registry it is located, then handling the pending requests, and then terminated.

Also, in order to terminate an empty pool, wouldn't you need to keep track of the amount of workers? In this case, you could take certain actions when you knew it became zero. So I wonder if this could be best implemented by allowing to send messages to the pool itself, instead of a given worker. Perhaps `NimblePool.pool_send` and `NimblePool.pool_send_after`. This way you can even implement your own pool ping?

**Comment by oliveigah** [comment]
> What happens if a checkout request is received between the timer going off and you terminating?

We already face this issue when terminating the pool with the `handle_ping/2` worker callback. We are addressing it in another issue: https://github.com/sneako/finch/issues/291. I made some improvements in https://github.com/sneako/finch/pull/292, but ultimately I believe the proper solution would be something similar to a graceful shutdown, as you described. However, it will be harder to implement. For now, since it is an edge case for an idle pool, I think a simple one-shot retry would be an easier more practical way to handle this race condition during idle termination.

> Also, in order to terminate an empty pool, would not you need to keep track of the number of workers? In this case, you could take certain actions when you knew it became zero.

I am not sure I understand this. We do not have any problems when the worker count "becomes" zero, because we do not terminate workers individually in handle_ping/2. Instead, we terminate the entire pool, so the worker count is either increasing or completely reset when the pool is terminated.

Our current problem happens when a lazy pool is started but no workers are initialized, and it stays that way for a long time. In that case, we have a pool that cannot be terminated because it has no workers.

Another possible situation is when some other part of the code terminates a worker, and we end up with an empty idle pool that also cannot be terminated, but afaict this is not the current issue.

I think `NimblePool.pool_send` and `NimblePool.pool_send_after` could help with both problems. However, I am not entirely sure how the implementation would look on the NimblePool side. It would just forward the messages to the pool and allow users to implement their own `handle_info/2` callbacks?

**Comment by josevalim** [comment]
Implementation wise I was thinking we would wrap the message in a special tuple that is unpacked and invokes `handle_pool_info` callback or similar.

**Comment by oliveigah** [comment]
> Implementation wise I was thinking we would wrap the message in a special tuple that is unpacked and invokes handle_pool_info callback or similar.

Ok, got it! I can take a look at handle_pool_info and open a PR. Does that sound good to you?
__

Regarding safe termination in multiple steps, I think it might be better to implement this directly in NimblePool, since it’s a problem any client using the pool termination feature could face. Do you think this would be possible and desirable?

I was thinking about exposing a new callback, such as `prepare_pool_termination/2`, which would receive the `pool_state` and `termination_reason`, and be called before `terminate_pool/1`. This could help clients implement their own safe termination logic.

Beyond that, do you think it would be possible for NimblePool to automatically handle deregistration of the pool process during this preparation step? Or should this still be the responsibility of the users? I'm not entirely sure about the best approach here either.

btw, I think it might be better to split this discussion into two issues. What do you think?
